#!/bin/sh

docker stop mock-json
docker rm mock-json
docker build . -t jgaa/mockjsonserver
docker run --name mock-json  -v `pwd`/db.json:/data/db.json -d -p 3000:80 jgaa/mockjsonserver
docker ps

echo 
echo "Run: 'docker stop mock-json' when you are done."
